import React, { useState } from 'react';

const PatientSummaryReport = () => {
    const [selectedRecord, setSelectedRecord] = useState(0);

    const reports = [
        {
            id: 'REP-2050-091',
            patient: 'Lubhanshu (Node: LUBHANSHU-25BCS10043)',
            symptoms: 'Acute chest tightness, systolic blood pressure elevation (185/115 mmHg), resting heart rate 104 bpm.',
            prediction: 'Hypertensive crisis trajectory with moderate vascular wall strain.',
            recommendation: 'Immediate systemic stabilization protocol, intravenous vasodilator administration.',
            riskLevel: 'HIGH (CRITICAL)',
            nextSteps: 'Isolate in quantum telemetry ward, monitor core coherence matrix every 15 minutes, restrict physical mobility.',
            disclaimer: 'MEDICAL DISCLAIMER: Generated by Healthcare Civilization 2050 AGI simulation against public reference telemetry. Not an official clinical diagnosis. Licensed medical supervision required.'
        },
        {
            id: 'REP-2050-092',
            patient: 'Cohort Subject Delta-7',
            symptoms: 'Cellular degradation markers elevated by 0.045%, chronic fatigue, irregular lipid profile.',
            prediction: 'Early-stage cellular oxidation cascade.',
            recommendation: 'Deploy Swarm Variant 8-B nanobots for targeted intercellular repair.',
            riskLevel: 'MODERATE (ELEVATED)',
            nextSteps: 'Schedule secondary QML diagnostic sweep in 72 hours, maintain hydration baseline.',
            disclaimer: 'MEDICAL DISCLAIMER: Generated by Healthcare Civilization 2050 AGI simulation against public reference telemetry. Not an official clinical diagnosis. Licensed medical supervision required.'
        }
    ];

    const current = reports[selectedRecord];

    const downloadReport = () => {
        const reportContent = `==================================================
HEALTHCARE CIVILIZATION 2050 - PATIENT SUMMARY REPORT
==================================================
REPORT ID: ${current.id}
PATIENT: ${current.patient}
TIMESTAMP: ${new Date().toISOString()}
--------------------------------------------------
1. SYMPTOMS & PRESENTATION:
${current.symptoms}

2. AGI PREDICTION & RECOMMENDATION:
Prediction: ${current.prediction}
Recommendation: ${current.recommendation}

3. RISK LEVEL:
${current.riskLevel}

4. NEXT-STEP GUIDANCE:
${current.nextSteps}
--------------------------------------------------
${current.disclaimer}
==================================================`;

        const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${current.id}_Summary_Report.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div style={{ width: '100%', fontFamily: '"Courier New", Courier, monospace' }}>
            <p style={{ color: 'gray', marginBottom: '20px', lineHeight: '1.6', fontSize: '0.9rem' }}>
                Automated Patient Summary Generator. Compile comprehensive diagnostic reports combining symptoms, risk levels, AGI predictions, and clinical next steps.
            </p>

            {/* Record Selector Tabs */}
            <div style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
                {reports.map((rep, idx) => (
                    <button
                        key={rep.id}
                        onClick={() => setSelectedRecord(idx)}
                        style={{
                            padding: '8px 14px',
                            backgroundColor: selectedRecord === idx ? '#083344' : '#050508',
                            border: `1px solid ${selectedRecord === idx ? '#22d3ee' : '#1e293b'}`,
                            color: selectedRecord === idx ? '#22d3ee' : '#64748b',
                            cursor: 'pointer',
                            fontFamily: '"Courier New", monospace',
                            fontSize: '0.75rem',
                            fontWeight: selectedRecord === idx ? 'bold' : 'normal'
                        }}
                    >
                        {rep.id}
                    </button>
                ))}
            </div>

            {/* Generated Report Card */}
            <div style={{
                backgroundColor: '#050508',
                border: '1px solid rgba(6,182,212,0.3)',
                borderRadius: '8px',
                padding: '24px',
                marginBottom: '20px'
            }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px dashed #1e293b', paddingBottom: '12px', marginBottom: '16px' }}>
                    <div>
                        <div style={{ color: '#06b6d4', fontWeight: 'bold', fontSize: '0.9rem' }}>{current.id}</div>
                        <div style={{ color: '#94a3b8', fontSize: '0.8rem' }}>{current.patient}</div>
                    </div>
                    <div style={{ color: current.riskLevel.includes('HIGH') ? '#ef4444' : '#f59e0b', fontWeight: 'bold', fontSize: '0.85rem' }}>
                        RISK: [{current.riskLevel}]
                    </div>
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', fontSize: '0.85rem', color: '#cbd5e1' }}>
                    <div>
                        <strong style={{ color: '#06b6d4', display: 'block', marginBottom: '4px' }}>SYMPTOMS & TELEMETRY:</strong>
                        <p style={{ margin: 0, color: '#94a3b8' }}>{current.symptoms}</p>
                    </div>
                    <div>
                        <strong style={{ color: '#06b6d4', display: 'block', marginBottom: '4px' }}>PREDICTION & RECOMMENDATION:</strong>
                        {/* Fixed arrow issue using &rarr; */}
                        <p style={{ margin: 0, color: '#94a3b8' }}>{current.prediction} &rarr; {current.recommendation}</p>
                    </div>
                    <div>
                        <strong style={{ color: '#06b6d4', display: 'block', marginBottom: '4px' }}>NEXT-STEP GUIDANCE:</strong>
                        <p style={{ margin: 0, color: '#94a3b8' }}>{current.nextSteps}</p>
                    </div>
                    <div style={{ backgroundColor: '#09090e', padding: '12px', borderRadius: '4px', border: '1px solid #1e293b', fontSize: '0.75rem', color: '#f59e0b', fontStyle: 'italic' }}>
                        {current.disclaimer}
                    </div>
                </div>
            </div>

            {/* Download Button */}
            <button
                onClick={downloadReport}
                style={{
                    width: '100%',
                    padding: '14px',
                    backgroundColor: 'rgba(6,182,212,0.1)',
                    border: '1px solid #06b6d4',
                    color: '#06b6d4',
                    cursor: 'pointer',
                    fontFamily: '"Courier New", monospace',
                    fontSize: '0.85rem',
                    fontWeight: 'bold',
                    letterSpacing: '2px',
                    textTransform: 'uppercase',
                    transition: 'all 0.2s ease'
                }}
                onMouseEnter={(e) => { e.currentTarget.style.background = '#06b6d4'; e.currentTarget.style.color = '#000'; }}
                onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(6,182,212,0.1)'; e.currentTarget.style.color = '#06b6d4'; }}
            >
                [ DOWNLOAD SUMMARY REPORT (JUDGE-READY EXPORT) ]
            </button>
        </div>
    );
};

export default PatientSummaryReport;