import React, { useMemo, useState, useEffect } from "react";

const bpClass = (s, d) => s >= 180 || d >= 120 ? ["URGENT RANGE","#ef4444"] : s >= 140 || d >= 90 ? ["HIGH RANGE","#f59e0b"] : s >= 130 || d >= 80 ? ["ELEVATED RANGE","#facc15"] : ["WITHIN REFERENCE RANGE","#10b981"];
const hrClass = h => h < 50 ? "Below typical resting reference range" : h > 100 ? "Above typical resting reference range" : "Within typical resting reference range";

export default function QuantumDiagnostics() {
 const [state,setState]=useState("IDLE"),[sys,setSys]=useState(""),[dia,setDia]=useState(""),[hr,setHr]=useState(""),[error,setError]=useState(""),[result,setResult]=useState(null),[history,setHistory]=useState([]),[progress,setProgress]=useState(0);
 useEffect(()=>{try{const x=localStorage.getItem("healthcare_2050_screening_ledger");if(x)setHistory(JSON.parse(x))}catch{}},[]);
 const bp=useMemo(()=>sys&&dia?bpClass(Number(sys),Number(dia)):null,[sys,dia]);
 const run=e=>{e.preventDefault();setError("");setResult(null);const s=Number(sys),d=Number(dia),h=Number(hr);
  if(![s,d,h].every(Number.isFinite)){setError("Enter systolic BP, diastolic BP and resting heart rate.");return}
  if(s<50||s>300||d<30||d>200||h<20||h>250){setError("One or more values are outside the supported input range.");return}
  setState("PROCESSING");setProgress(10);const started=performance.now();const t=setInterval(()=>setProgress(p=>Math.min(95,p+15)),120);
  setTimeout(()=>{clearInterval(t);const b=bpClass(s,d);const r={id:"SCR-"+Date.now().toString(36).toUpperCase(),timestamp:new Date().toISOString(),vitals:{systolic:s,diastolic:d,restingHeartRate:h},bloodPressure:b[0],heartRate:hrClass(h),urgency:s>=180||d>=120?"URGENT MEDICAL REVIEW":"NON-URGENT SCREENING",processingMs:Math.round(performance.now()-started)};setProgress(100);setState("COMPLETE");setResult(r);setHistory(prev=>{const n=[r,...prev].slice(0,20);try{localStorage.setItem("healthcare_2050_screening_ledger",JSON.stringify(n))}catch{}return n})},850)
 };
 const clear=()=>{setSys("");setDia("");setHr("");setError("");setResult(null);setState("IDLE");setProgress(0)};
 const exportFHIR=r=>{const x={resourceType:"Bundle",type:"collection",timestamp:r.timestamp,entry:[{resource:{resourceType:"Observation",id:r.id,status:"final",category:[{coding:[{system:"http://terminology.hl7.org/CodeSystem/observation-category",code:"vital-signs"}]}],code:{text:"Blood pressure and resting heart rate screening inputs"},component:[{code:{coding:[{system:"http://loinc.org",code:"8480-6"}]},valueQuantity:{value:r.vitals.systolic,unit:"mmHg"}},{code:{coding:[{system:"http://loinc.org",code:"8462-4"}]},valueQuantity:{value:r.vitals.diastolic,unit:"mmHg"}},{code:{coding:[{system:"http://loinc.org",code:"8867-4"}]},valueQuantity:{value:r.vitals.restingHeartRate,unit:"beats/minute"}}]}}]};const u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/fhir+json"}));const a=document.createElement("a");a.href=u;a.download="Healthcare2050_"+r.id+".json";a.click();URL.revokeObjectURL(u)};
 return <div style={{width:"100%",maxWidth:900,margin:"20px auto",padding:24,background:"#050508",border:"1px solid rgba(6,182,212,.3)",borderRadius:16,color:"#cffafe",fontFamily:'"Courier New",monospace',boxSizing:"border-box"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:20,borderBottom:"1px solid rgba(6,182,212,.2)",paddingBottom:16,marginBottom:20}}><div><h2 style={{margin:0,color:"#22d3ee",letterSpacing:2}}>HEALTH SCREENING CORE</h2><p style={{margin:"6px 0 0",color:"#0891b2",fontSize:".72rem",letterSpacing:1.5}}>2050 CONCEPT UI • REFERENCE-BASED SCREENING</p></div><b style={{color:state==="PROCESSING"?"#f59e0b":"#10b981"}}>[{state}]</b></div>
  <div style={{padding:12,marginBottom:18,border:"1px solid #164e63",background:"rgba(8,47,73,.35)",color:"#a5f3fc",fontSize:".72rem",lineHeight:1.6}}>Software demonstration for organizing health measurements. It does not diagnose disease, prescribe treatment, contact clinicians, or measure quantum states.</div>
  {error&&<div style={{padding:12,marginBottom:16,border:"1px solid #ef4444",color:"#fca5a5",background:"rgba(127,29,29,.25)"}}>{error}</div>}
  <form onSubmit={run}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>{[["SYSTOLIC BP",sys,setSys,"mmHg"],["DIASTOLIC BP",dia,setDia,"mmHg"],["RESTING HEART RATE",hr,setHr,"bpm"]].map(([l,v,s,p])=><label key={l} style={{color:"#94a3b8",fontSize:".7rem"}}>{l}<input type="number" value={v} onChange={e=>s(e.target.value)} placeholder={p} style={{width:"100%",marginTop:7,padding:11,boxSizing:"border-box",background:"#030712",border:"1px solid #1e293b",color:"#cffafe"}}/></label>)}</div>
  {bp&&<div style={{marginTop:12,color:bp[1],fontWeight:"bold",fontSize:".75rem"}}>REFERENCE CHECK: {bp[0]}</div>}
  <button type="submit" disabled={state==="PROCESSING"} style={{marginTop:16,width:"100%",padding:12,background:"rgba(6,182,212,.1)",border:"1px solid #06b6d4",color:"#22d3ee"}}>{state==="PROCESSING"?"PROCESSING "+progress+"%":"RUN SCREENING"}</button><button type="button" onClick={clear} style={{marginTop:8,width:"100%",padding:10,background:"transparent",border:"1px solid #1e293b",color:"#64748b"}}>CLEAR</button></form>
  {result&&<div style={{marginTop:20,padding:18,border:"1px solid "+(bp?.[1]||"#10b981")+"55",background:"rgba(2,6,23,.7)"}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>SCREENING RESULT</strong><span style={{color:"#64748b",fontSize:".7rem"}}>{result.id}</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10,marginTop:14}}><div><small>BLOOD PRESSURE</small><div style={{color:bp?.[1]}}>{result.bloodPressure}</div></div><div><small>HEART RATE</small><div>{result.heartRate}</div></div><div><small>URGENCY</small><div style={{color:result.urgency.startsWith("URGENT")?"#ef4444":"#10b981"}}>{result.urgency}</div></div><div><small>PROCESSING</small><div>{result.processingMs} ms</div></div></div><p style={{color:"#94a3b8",fontSize:".7rem",lineHeight:1.6}}>A reference range is not a diagnosis. Concerning measurements or severe symptoms warrant appropriate medical care.</p><button onClick={()=>exportFHIR(result)} style={{padding:"9px 12px",background:"transparent",border:"1px solid #06b6d4",color:"#22d3ee"}}>EXPORT FHIR JSON</button></div>}
  {history.length>0&&<div style={{marginTop:22,borderTop:"1px solid #1e293b",paddingTop:16}}><div style={{color:"#64748b",fontSize:".68rem",letterSpacing:1.5,marginBottom:10}}>LOCAL SCREENING HISTORY</div>{history.slice(0,5).map(x=><div key={x.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"8px 0",borderBottom:"1px solid #111827",fontSize:".7rem"}}><span>{x.id}</span><span>{x.vitals.systolic}/{x.vitals.diastolic} • {x.vitals.restingHeartRate} bpm</span><span style={{color:x.urgency.startsWith("URGENT")?"#ef4444":"#10b981"}}>{x.urgency}</span></div>)}</div>}
 </div>
}